export const data = [
  {
    id: 1,
    name: "Tabby Town",
    location: "Gunung Batu, Indonesia",
    mainImage: "/images/backyard-image1.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 2,
    name: "Anggana",
    location: "Bogor, Indonesia",
    mainImage: "/images/backyard-image2.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 3,
    name: "Seattle Rain",
    location: "Jakarta, Indonesia",
    mainImage: "/images/backyard-image3.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 4,
    name: "Wooden Pit",
    location: "Wonosobo, Indonesia",
    mainImage: "/images/backyard-image4.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 5,
    name: "Green Park",
    location: "Tangerang, Indonesia",
    mainImage: "/images/living-room-img1.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 6,
    name: "Podo Wae",
    location: "Madiun, Indonesia",
    mainImage: "/images/livingroom-img2.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 7,
    name: "Silver Rain",
    location: "Bandung, Indonesia",
    mainImage: "/images/livingroom-img3.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 8,
    name: "Cashville",
    location: "Kemang Indonesia",
    mainImage: "/images/livingroom-img4.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 9,
    name: "Ps Wood",
    location: "Depok, Indonesia",
    mainImage: "/images/kitchen-img1.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 10,
    name: "One Five",
    location: "Jakarta, Indonwsia",
    mainImage: "/images/kitchen-img2.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 11,
    name: "Minimal",
    location: "Bagor, Indonesia",
    mainImage: "/images/kitchen-img3.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
  {
    id: 12,
    name: "Stays Home",
    location: "Wanosobo, Indonesia",
    mainImage: "/images/kitchen-img4.svg",
    images: [
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643184/pic_fzavh5.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643183/ppic4_rz8evw.png",
      "https://res.cloudinary.com/dnajwdxn9/image/upload/v1741643182/image4_ucfagj.png",
    ],
    description:
      "A cozy retreat surrounded by lush greenery, perfect for a quiet getaway.",
    pricePerNight: 280,
    duration: 2,
    features: {
      bedrooms: 3,
      bathrooms: 3,
      livingRoom: 1,
      diningRoom: 1,
      internetSpeed: "10 mbps",
      unitsReady: 2,
      refrigerators: 2,
      television: 4,
    },
  },
];


